### ISSUE TITLE
percent_num_progress_bar.sh 27行 变量获取不到值，导致sleep 参数错误

### ISSUE THREAD

**Issue by lmhaoye** [FISCO-BCOS/fisco-package-build-tool#12]
`percent_num_progress_bar.sh` 27行 变量获取不到值，导致sleep 参数错误

·interval=$(bc <<< "scale=2; $total_sec/100")·  执行有问题。。
不知道是哪一块出了问题

**Comment by flowhub-dev** [comment]
先通过命令后安装bc，如centos下sudo yum install -y bc

**Comment by fisco-dev** [comment]
谢谢反馈， 这个我们会很快修复。
