### ISSUE TITLE
Cannot be installed properly

### ISSUE THREAD

**Issue by cristicmf** [FISCO-BCOS/fisco-package-build-tool#20]
[  6%] Performing download step (download, verify and extract) for 'secp256k1'
-- verifying file...
       file='/home/app/workspace/v3/package-tool/FISCO-BCOS/deps/src/secp256k1-9d560f99.tar.gz'
-- SHA256 hash of
    /home/app/workspace/v3/package-tool/FISCO-BCOS/deps/src/secp256k1-9d560f99.tar.gz
  does not match expected value
    expected: '910b2535bdbb5d235e9212c92050e0f9b327e05129b449f8f3d3c6d558121284'
      actual: '580d232fe8b23bd5997ce18b1504b2c655d7c9b1de06b65bfbc6fcafabf0735f'
-- File already exists but hash mismatch. Removing...
-- Downloading...
   dst='/home/app/workspace/v3/package-tool/FISCO-BCOS/deps/src/secp256k1-9d560f99.tar.gz'
   timeout='none'
-- Using src='https://github.com/bitcoin-core/secp256k1/archive/9d560f992db26612ce2630b194aef5f44d63a530.tar.gz'

**Comment by ywy2090** [comment]
可以将代码重新拉取一下，这个是1.3.1之前的一个bug，我们会在后续版本进行修复。
