### ISSUE TITLE
脚本缺少运行权限

### ISSUE THREAD

**Issue by artemis-my** [FISCO-BCOS/fisco-package-build-tool#24]
使用下载的压缩包部署，build过程中会报如下运行权限问题，导致部分位置没有相应的百分比进度
![_20180801152128](https://user-images.githubusercontent.com/25951395/43507070-a6ece054-959e-11e8-94f6-0d496c57912a.png)

**Comment by shijiaxing-cm** [comment]
补充说明：仅采用downloadZIP的方式会出现上述问题，clone不影响。

**Comment by fisco-dev** [comment]
你当前登录的用户是哪个？ 在fisco-package-build-tool目录下执行下ls -lt,我看下结果。 可能是压缩下载的时候一些权限被去掉了。

**Comment by artemis-my** [comment]
![image](https://user-images.githubusercontent.com/25951395/43507876-d89f3582-95a0-11e8-9f44-df1267f3ef24.png)
其中generate_installation_packages.sh脚本本来也没有权限，还是手动加的，感觉对应文档位置也需要说明一下

**Comment by shijiaxing-cm** [comment]
已经提交PR，在脚本中，增加赋权操作（#25）
